plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Make Firebase static, without forcing use_frameworks!
$RNFirebaseAsStaticFramework = true

target 'TestBackButton' do
  config = use_native_modules!

  # IMPORTANT: DO NOT USE use_frameworks! anywhere

  # KEEP Firebase static-framework
  pod 'FirebaseCore',           :build_type => :static_framework
  pod 'FirebaseCoreInternal',   :build_type => :static_framework
  pod 'FirebaseAuth',           :build_type => :static_framework
  pod 'FirebaseFirestore',      :build_type => :static_framework
  pod 'FirebaseFirestoreInternal', :build_type => :static_framework
  pod 'FirebaseFunctions',      :build_type => :static_framework
  pod 'FirebaseStorage',        :build_type => :static_framework
  pod 'FirebaseMessagingInterop', :build_type => :static_framework, :modular_headers => true
  pod 'GoogleUtilities',        :build_type => :static_framework
  
  # Facebook SDK
  pod 'FBSDKCoreKit',           :build_type => :static_framework
  pod 'FBSDKLoginKit',          :build_type => :static_framework
  
  # SHA256
  pod 'RNSha256', :path => '../node_modules/react-native-sha256'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
